inherit_from: .rubocop_todo.yml

require:
  - rubocop-rails
  - rubocop-rspec

Style/Documentation:
  Enabled: false

RSpec/MultipleExpectations:
  Enabled: false

Metrics/MethodLength:
  Enabled: false

AllCops:
  NewCops: enable
