# frozen_string_literal: true

require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to test the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator. If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails. There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.

RSpec.describe '/property_enquiries' do
  # This should return the minimal set of attributes required to create a valid
  # PropertyEnquiry. As you add validations to PropertyEnquiry, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) do
    skip('Add a hash of attributes valid for your model')
  end

  let(:invalid_attributes) do
    skip('Add a hash of attributes invalid for your model')
  end

  describe 'GET /index' do
    it 'renders a successful response' do
      PropertyEnquiry.create! valid_attributes
      get property_enquiries_url
      expect(response).to be_successful
    end
  end

  describe 'GET /show' do
    it 'renders a successful response' do
      property_enquiry = PropertyEnquiry.create! valid_attributes
      get property_enquiry_url(property_enquiry)
      expect(response).to be_successful
    end
  end

  describe 'GET /new' do
    it 'renders a successful response' do
      get new_property_enquiry_url
      expect(response).to be_successful
    end
  end

  describe 'GET /edit' do
    it 'renders a successful response' do
      property_enquiry = PropertyEnquiry.create! valid_attributes
      get edit_property_enquiry_url(property_enquiry)
      expect(response).to be_successful
    end
  end

  describe 'POST /create' do
    context 'with valid parameters' do
      it 'creates a new PropertyEnquiry' do
        expect do
          post property_enquiries_url, params: { property_enquiry: valid_attributes }
        end.to change(PropertyEnquiry, :count).by(1)
      end

      it 'redirects to the created property_enquiry' do
        post property_enquiries_url, params: { property_enquiry: valid_attributes }
        expect(response).to redirect_to(property_enquiry_url(PropertyEnquiry.last))
      end
    end

    context 'with invalid parameters' do
      it 'does not create a new PropertyEnquiry' do
        expect do
          post property_enquiries_url, params: { property_enquiry: invalid_attributes }
        end.not_to change(PropertyEnquiry, :count)
      end

      it "renders a response with 422 status (i.e. to display the 'new' template)" do
        post property_enquiries_url, params: { property_enquiry: invalid_attributes }
        expect(response).to have_http_status(:unprocessable_entity)
      end
    end
  end

  describe 'PATCH /update' do
    context 'with valid parameters' do
      let(:new_attributes) do
        skip('Add a hash of attributes valid for your model')
      end

      it 'updates the requested property_enquiry' do
        property_enquiry = PropertyEnquiry.create! valid_attributes
        patch property_enquiry_url(property_enquiry), params: { property_enquiry: new_attributes }
        property_enquiry.reload
        skip('Add assertions for updated state')
      end

      it 'redirects to the property_enquiry' do
        property_enquiry = PropertyEnquiry.create! valid_attributes
        patch property_enquiry_url(property_enquiry), params: { property_enquiry: new_attributes }
        property_enquiry.reload
        expect(response).to redirect_to(property_enquiry_url(property_enquiry))
      end
    end

    context 'with invalid parameters' do
      it "renders a response with 422 status (i.e. to display the 'edit' template)" do
        property_enquiry = PropertyEnquiry.create! valid_attributes
        patch property_enquiry_url(property_enquiry), params: { property_enquiry: invalid_attributes }
        expect(response).to have_http_status(:unprocessable_entity)
      end
    end
  end

  describe 'DELETE /destroy' do
    it 'destroys the requested property_enquiry' do
      property_enquiry = PropertyEnquiry.create! valid_attributes
      expect do
        delete property_enquiry_url(property_enquiry)
      end.to change(PropertyEnquiry, :count).by(-1)
    end

    it 'redirects to the property_enquiries list' do
      property_enquiry = PropertyEnquiry.create! valid_attributes
      delete property_enquiry_url(property_enquiry)
      expect(response).to redirect_to(property_enquiries_url)
    end
  end
end
